package ops

func BuiltinSpecs() []OperationSpec {
	return []OperationSpec{
		{
			Op:                 "inspect_workbook",
			Version:            "v1",
			Level:              LevelReadOnly,
			Risk:               RiskLow,
			ConfirmationPolicy: ConfirmNever,
			Description:        "Inspect workbook sheets and structure.",
			UserPhrases:        []string{"查看工作簿", "看看有哪些 sheet", "理解这个文件"},
			Tags:               []string{"read", "workbook", "structure"},
		},
		{
			Op:                 "find",
			Version:            "v1",
			Level:              LevelLocate,
			Risk:               RiskLow,
			ConfirmationPolicy: ConfirmNever,
			Description:        "Find rows or cells by text query.",
			UserPhrases:        []string{"查找", "定位", "在哪一行", "找到"},
			Tags:               []string{"read", "locate", "search"},
			RequiredArgs:       []string{"sheet", "query"},
		},
		{
			Op:                 "get_range",
			Version:            "v1",
			Level:              LevelReadOnly,
			Risk:               RiskLow,
			ConfirmationPolicy: ConfirmNever,
			Description:        "Read a range of cells.",
			UserPhrases:        []string{"读取范围", "看一下 A1:D10", "获取这些单元格"},
			Tags:               []string{"read", "range"},
			RequiredArgs:       []string{"sheet", "range"},
		},
		{
			Op:                 "aggregate",
			Version:            "v1",
			Level:              LevelReadOnly,
			Risk:               RiskLow,
			ConfirmationPolicy: ConfirmNever,
			Description:        "Aggregate numeric values in a column.",
			UserPhrases:        []string{"求和", "平均值", "统计数量"},
			Tags:               []string{"read", "aggregate", "numeric"},
			RequiredArgs:       []string{"sheet", "column", "type"},
		},
		{
			Op:                 "update_cell",
			Version:            "v1",
			Level:              LevelCellEdit,
			Risk:               RiskLow,
			ConfirmationPolicy: ConfirmSometimes,
			Description:        "Overwrite a single cell value.",
			UserPhrases:        []string{"修改单元格", "把 B2 改成", "设置单元格"},
			Tags:               []string{"write", "cell"},
			RequiredArgs:       []string{"sheet", "cell", "value"},
		},
		{
			Op:                 "clear_cell",
			Version:            "v1",
			Level:              LevelCellEdit,
			Risk:               RiskLow,
			ConfirmationPolicy: ConfirmSometimes,
			Description:        "Clear an existing cell without shifting surrounding cells.",
			UserPhrases:        []string{"清空单元格", "把这个格子清掉", "删除单元格内容"},
			Tags:               []string{"write", "cell", "clear"},
			RequiredArgs:       []string{"sheet", "cell"},
		},
		{
			Op:                 "batch_update",
			Version:            "v1",
			Level:              LevelRangeEdit,
			Risk:               RiskMedium,
			ConfirmationPolicy: ConfirmSometimes,
			Description:        "Update multiple cells selected by range or search scope.",
			UserPhrases:        []string{"批量修改", "把这些行都改成", "给整列打折"},
			Tags:               []string{"write", "range", "batch"},
			RequiredArgs:       []string{"sheet", "scope", "action"},
		},
		{
			Op:                 "create_sheet",
			Version:            "v1",
			Level:              LevelStructureEdit,
			Risk:               RiskMedium,
			ConfirmationPolicy: ConfirmSometimes,
			Description:        "Create a new worksheet.",
			UserPhrases:        []string{"新建 sheet", "创建工作表", "新增一个表", "加一个空白页"},
			Tags:               []string{"write", "sheet", "create", "structure"},
			RequiredArgs:       []string{"sheet"},
			OptionalArgs:       []string{"after_sheet"},
			Preconditions:      []string{"sheet name must not already exist"},
			Postconditions:     []string{"workbook contains the new sheet"},
			CanUndo:            true,
		},
		{
			Op:                 "insert_cells",
			Version:            "v1",
			Level:              LevelStructureEdit,
			Risk:               RiskMedium,
			ConfirmationPolicy: ConfirmSometimes,
			Description:        "Insert blank cells and shift existing cells right or down.",
			UserPhrases:        []string{"插入空白单元格", "新增空白格", "让右边数据后移"},
			Tags:               []string{"write", "cell", "insert", "structure"},
			RequiredArgs:       []string{"sheet", "cell", "shift"},
		},
		{
			Op:                 "delete_sheet",
			Version:            "v1",
			Level:              LevelDestructive,
			Risk:               RiskHigh,
			ConfirmationPolicy: ConfirmAlways,
			Description:        "Delete a worksheet.",
			UserPhrases:        []string{"删除 sheet", "删掉工作表", "移除这个表"},
			Tags:               []string{"write", "sheet", "delete", "destructive"},
			RequiredArgs:       []string{"sheet"},
		},
		{
			Op:                 "save_as",
			Version:            "v1",
			Level:              LevelExternalWrite,
			Risk:               RiskMedium,
			ConfirmationPolicy: ConfirmSometimes,
			Description:        "Save the workbook to a path.",
			UserPhrases:        []string{"保存为", "导出到", "另存"},
			Tags:               []string{"save", "external_write"},
			RequiredArgs:       []string{"path"},
		},
	}
}
